import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "outline-variant": "#c5c8b7",
        "tertiary": "#662e63",
        "on-tertiary-container": "#ffc0f5",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#370237",
        "primary-container": "#4b6319",
        "on-primary-container": "#c1de86",
        "surface-tint": "#4e661c",
        "on-primary-fixed": "#141f00",
        "on-background": "#1a1c1b",
        "secondary": "#576341",
        "tertiary-fixed": "#ffd7f6",
        "surface-bright": "#f9f9f7",
        "on-secondary-container": "#5d6946",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e3e1",
        "surface-variant": "#e2e3e1",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#6a3166",
        "surface-container-high": "#e8e8e6",
        "secondary-fixed": "#dbe8bd",
        "on-surface": "#1a1c1b",
        "surface-container-low": "#f4f4f2",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f1f1ef",
        "primary-fixed": "#cfee93",
        "tertiary-container": "#81467c",
        "primary": "#4b6319",
        "tertiary-fixed-dim": "#f7afed",
        "inverse-primary": "#b4d17a",
        "surface-container": "#eeeeec",
        "inverse-surface": "#2f3130",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "on-surface-variant": "#45483b",
        "on-primary-fixed-variant": "#374e03",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b4d17a",
        "background": "#ffffff",
        "secondary-container": "#dbe8bd",
        "on-secondary-fixed": "#151e04",
        "surface-dim": "#dadad8",
        "secondary-fixed-dim": "#bfcca2",
        "on-secondary-fixed-variant": "#404b2b",
        "outline": "#75796a",
        "on-tertiary": "#ffffff",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        sans: ["Raleway", "sans-serif"],
        serif: ["Raleway", "sans-serif"],
        mono: ["Raleway", "sans-serif"],
        "headline": ["Raleway", "sans-serif"],
        "body": ["Raleway", "sans-serif"],
        "label": ["Raleway", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
